### ISSUE TITLE
Review for 0.2.16

### ISSUE THREAD

**Issue by fmorgner** [umurmur/umurmur#57]
We are at a point at which it might be useful to tag a new release.

We fixed the banning and reworked the timer code, added a new TLS backend and a shared memory API. I think, that i would be a good time to do a review of the current code and verify that the current master build on out target systems. It would be nice if as much people as possible do some testing so we can see if there are any release blocking bugs in the code.

**Comment by fatbob313** [comment]
I agree. There are a couple of issues over at GoogleCode I worked on a bit before Christmas but never came to a definite solution. I don't think any of them are showstoppers for a new release though.
One of them is https://code.google.com/p/umurmur/issues/detail?id=44 - Couldn't come up with a neat way to check file access before switching user. I think we'll just document the fact and be happy with it, unless someone's sitting on a nice way to do it.

**Comment by fmorgner** [comment]
I think you are right. Especially handling the log-file access checks would be, at least at the moment, nice to have but not required. I will do some testing on Net- and OpenBSD as well as OS X and Gentoo over the weekend. As I do development on OS X and Gentoo I don't expect any major problems on that side, OpenBSD, at least to me, seems fairly quirky at points.

I can't verify functionality on OpenWRT, Synology and the like though.

**Comment by fatbob313** [comment]
Compiles and runs fine on OpenWRT using PolarSSL-1.3.10 (or MbedTLS as it's called nowadays). I haven't tried OpenSSL but I don't expect any problems there. PolarSSL has a history of changing the library interface pretty often though...

**Comment by hasufell** [comment]
Works on gentoo with polarssl, libressl-2.1.3 and gnutls-3.3.10. However, it doesn't compile with gnutls-2.12.23, although it configures successfully. Maybe the configure script should choke on an unsupported version?

I always get this compiler warning:
```
ban.c:274:3: warning: implicit declaration of function 'strptime' is invalid in C99
      [-Wimplicit-function-declaration]
                strptime(start, "%Y-%m-%dT%H:%M:%S", &timespec);
                ^
```

**Comment by fmorgner** [comment]
Nice work, thank you both. @hasufell what error message do you get when compiling with the older GnuTLS version? Would be great to know, as we could work out what the lowest version supported is, and possibly support older versions too. I'll be looking into the warning later. Thanks again!

**Comment by hasufell** [comment]
```
make[2]: Entering directory '/home/jule/git/umurmur/src'
clang -DHAVE_CONFIG_H -I.     -g -O2 -MT client.o -MD -MP -MF .deps/client.Tpo -c -o client.o client.c
client.c:522:48: error: use of undeclared identifier 'GNUTLS_E_PREMATURE_TERMINATION'
                        else if (SSLi_get_error(client->ssl, rc) == SSLI_ERROR_ZERO_RETURN ||
                                                                    ^
./ssl.h:97:32: note: expanded from macro 'SSLI_ERROR_ZERO_RETURN'
#define SSLI_ERROR_ZERO_RETURN GNUTLS_E_PREMATURE_TERMINATION
                               ^
client.c:528:44: error: use of undeclared identifier 'GNUTLS_E_PREMATURE_TERMINATION'
                                if (SSLi_get_error(client->ssl, rc) == SSLI_ERROR_SYSCALL) {
                                                                       ^
./ssl.h:99:28: note: expanded from macro 'SSLI_ERROR_SYSCALL'
#define SSLI_ERROR_SYSCALL GNUTLS_E_PREMATURE_TERMINATION
                           ^
client.c:535:49: error: use of undeclared identifier 'GNUTLS_E_PREMATURE_TERMINATION'
                                else if (SSLi_get_error(client->ssl, rc) == SSLI_ERROR_CONNRESET) {
                                                                            ^
./ssl.h:98:30: note: expanded from macro 'SSLI_ERROR_CONNRESET'
#define SSLI_ERROR_CONNRESET GNUTLS_E_PREMATURE_TERMINATION
                             ^
client.c:591:43: error: use of undeclared identifier 'GNUTLS_E_PREMATURE_TERMINATION'
                        if (SSLi_get_error(client->ssl, rc) == SSLI_ERROR_SYSCALL) {
                                                               ^
./ssl.h:99:28: note: expanded from macro 'SSLI_ERROR_SYSCALL'
#define SSLI_ERROR_SYSCALL GNUTLS_E_PREMATURE_TERMINATION
                           ^
client.c:594:48: error: use of undeclared identifier 'GNUTLS_E_PREMATURE_TERMINATION'
                        else if (SSLi_get_error(client->ssl, rc) == SSLI_ERROR_CONNRESET) {
                                                                    ^
./ssl.h:98:30: note: expanded from macro 'SSLI_ERROR_CONNRESET'
#define SSLI_ERROR_CONNRESET GNUTLS_E_PREMATURE_TERMINATION
                             ^
5 errors generated.
Makefile:398: recipe for target 'client.o' failed
```

**Comment by fmorgner** [comment]
Thanks, this macro was introduced with 2.99.3 so I assume we would be save starting with this version, but the better alternative would be to check for at least 3.0. I'm fixing this in the build setup.

**Comment by fmorgner** [comment]
Version 0.2.16 codename 'Agrajag' has been released today.
