### ISSUE TITLE
PolarSSL 1.1.1 compatibility

### ISSUE THREAD

**Issue by Diaoul** [umurmur/umurmur#5]
```
/home/spksrc/spksrc/toolchains/syno-88f6281/work/arm-none-linux-gnueabi/bin/arm-none-linux-gnueabi-gcc -DHAVE_CONFIG_H -I. -I..   -I/home/spksrc/spksrc/cross/umurmur/work-88f6281/install//usr/local/include   -I/home/spksrc/spksrc/cross/umurmur/work-88f6281/install//usr/local/include  -MT ssl.o -MD -MP -MF .deps/ssl.Tpo -c -o ssl.o ssl.c
ssl.c: In function 'SSLi_newconnection':
ssl.c:190: error: 'havege_rand' undeclared (first use in this function)
ssl.c:190: error: (Each undeclared identifier is reported only once
ssl.c:190: error: for each function it appears in.)
```

Works fine with PolarSSL 1.0.0 though
